name: Build Strapi
on:
  push:
    branches:
      - main

jobs:
  build-strapi:
    runs-on: ubuntu-latest
    steps:
      # 1️⃣ Clonar el repositorio
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Configurar Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      # 3️⃣ Instalar dependencias
      - name: Install dependencies
        run: npm ci

      # 4️⃣ Build Strapi
      - name: Build Strapi
        run: npm run build
